[package]
name = "bril-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bril-nw = { path = "../bril-nw" }
clap = { version = "3.1.12", features = ["cargo"] }
